### ISSUE TITLE
Create user chip

### ISSUE THREAD

**Issue by Jameskmonger** [noodlecrate/noodlecrate.github.io#7]
Create a user chip like this:

![Image of user chip](http://i.imgur.com/NLzMZyn.png)

**Comment by Jameskmonger** [comment]
@jamesrichford fancy having a crack at this? I attempted it but it wasn't great, so I photoshopped the image above.

**Comment by jamesadarich** [comment]
@Jameskmonger - have a peek, see what you think

**Comment by Jameskmonger** [comment]
Looks great to me @jamesrichford!

The `h1` element seems to be stretching all the way across.. why is this? (see [here](http://i.imgur.com/HAhePIG.png))

**Comment by jamesadarich** [comment]
Because the chip is floating. Did it as a quick style while we're still finalising menus etc :)
